remote_theme: pages-themes/architect@v0.2.0 
title: [An Overview of Eid al-Adha]
description: [A website with information on the history, purpose, festivities, and my own personal stories of Eid al-Adha.]
